### ISSUE TITLE
config file generation for first time

### ISSUE THREAD

**Issue by feds01** [feds01/photo#5]
At the moment config file was manually created, when the script is used on a different environment it needs to be independent of user creating files manually.

**Comment by MeWasabi** [comment]
I suggest creating a separate module for generating the config rather than adding it to "utils.py", so call it conf_gen.py". Also this module should be responsible for not only the config file integrity, but also changing and retrieving config information.

**Comment by feds01** [comment]
coming to version v0.6

**Comment by feds01** [comment]
added in  b390576ef86d8aa3789e3855a1a0b142723b3cc6
